sudo: required
language: python
python:
  - '3.6'
services:
  - docker
before_install:
  - eval "$(ssh-agent -s)"
install:
script:
  - make prepare
  - make docker
  - make run
  - make ssh-push
  - make git-push
cache:
  directories:
    - repository
