sudo: required
language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_132d63ea0a65_key -iv $encrypted_132d63ea0a65_iv -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - make ssh

script:
  - make all

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    secure: K2HUffs/4DO+PNmgzRgHUOpH8RDHCtzu5r5/4hsarsDekjq5zS7gqgCtwrEFL6O9Bt86x+FzBnvfOJ/iS0JLIWYmWHmstz3Fd3h0+TdW+Nl8ubS2wYV/jDk/VF6MND4h3VFXGbhrZ2LyjOqmrSxOzjQV7TBHLdtg5d16ZUGuaeQ8smwtvej5QFuVQd0nh5lA4D45OYEfSX1Z7G1iPMzqBRNLWSlILSK1OEaFZtLKYDjYMaFjsVvG8tLc7oLByRKmocetfQmHTi4JGEv6irAc4yugEjkN05Q6QsssUZDR4u3WalHOd9cfqZm0kugni4ANiWPeDC73GNJucK9R2iFBRva7l2l8hawywT/3Pp2Uco8Zb3F3zXRl7PqdWd3UIAb4SKWA8dwunkqqV31k2cbYfy2eOb1sO8412l21LUdNBYI5dO3o0iwMETCrcEp30B0T0GaYtOILdMLsDOPiEPwIDVIk9fK78bzr1Ac1tUnDqqFcOdH7ojuxH4sPzmRo45H42dD5SvlS2FFW0FeIdHwdkrQAh4yzk7t2qwVRuvWJ6zTvNIPwR7dQ1mP7wqGVK7qJ8LEbDf5UyMmc9SPOCuyO56o8ddeb3Xca20ntmivl8xbiAs7kWrx4uZrzjTsmsb8SnErPBNiBnKxqIkbYHQ/a5yahOYNx4BqOJ4ih6+aYpmQ=
