sudo: required
language: python
python:
  - '3.6'
services:
  - docker
before_install:
  - eval "$(ssh-agent -s)"
install:
script:
  - make docker
  - make run
  - make deploy
cache:
  directories:
    - mirror
