sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - eval "$(ssh-agent -s)"
install:
script:
  - make prepare
  - make docker
  - make run
  - make git-push
  - make ssh-push
cache:
  directories:
    - repository
