sudo: required
language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_9f227eff80a0_key -iv $encrypted_9f227eff80a0_iv -in deploy_rsa.enc -out ./deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_rsa
- echo -e "Host lognoz.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_rsa
- ssh -i ./deploy_rsa lognozc@lognoz.org pwd
