sudo: required
language: generic
services:
- docker
install:
script:
  - make container
  - make run
cache:
  directories:
  - mirror
before_install:
  - openssl aes-256-cbc -K $encrypted_3f01c25f3d95_key -iv $encrypted_3f01c25f3d95_iv -in secrets.tar.enc -out ./secrets.tar -d
  - tar xvf secrets.tar
  - touch repository.yml.enc
  - touch deploy_key.enc
