sudo: required
language: python
python:
- '3.6'
addons:
  ssh_known_hosts: "lognoz.org"
before_install:
- openssl aes-256-cbc -K $encrypted_9f227eff80a0_key -iv $encrypted_9f227eff80a0_iv -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
- ssh -i ./deploy_key lognozc@lognoz.org pwd
